apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    run: nginx-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx-deployment
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: 346573986387.dkr.ecr.us-east-1.amazonaws.com/udacity_capstone:v1
        name: nginx-deployment
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80 
status: {}
